

services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
 #     POSTGRES_DB: demo_db          # 自己改
      POSTGRES_USER: demo_user      # 自己改
      POSTGRES_PASSWORD: demo_pass  # 自己改，别用默认到生产
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one:1.75.0
    container_name: jaeger
    restart: always
    ports:
      # UI
      - "16686:16686"
      # OTLP gRPC（给 OpenTelemetry SDK / Spring Boot Otel 用）
      - "4317:4317"
      # OTLP HTTP（如果你用 HTTP exporter）
      - "4318:4318"
      # 传统 Jaeger 协议/Agent 端口（按需开启）
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "14268:14268"
      - "14250:14250"
    environment:
      COLLECTOR_OTLP_ENABLED: "true"

      # 如果你只想用 OTLP，可以不用改其他配置

volumes:
  pg_data: